# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\chat_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_chat_interface(object):
    def setupUi(self, chat_interface):
        chat_interface.setObjectName("chat_interface")
        chat_interface.resize(687, 607)
        self.centralwidget = QtWidgets.QWidget(chat_interface)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.chat_history = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.chat_history.sizePolicy().hasHeightForWidth())
        self.chat_history.setSizePolicy(sizePolicy)
        self.chat_history.setObjectName("chat_history")
        self.verticalLayout.addWidget(self.chat_history)
        self.text_input = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.text_input.sizePolicy().hasHeightForWidth())
        self.text_input.setSizePolicy(sizePolicy)
        self.text_input.setObjectName("text_input")
        self.verticalLayout.addWidget(self.text_input)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.send_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.send_btn.sizePolicy().hasHeightForWidth())
        self.send_btn.setSizePolicy(sizePolicy)
        self.send_btn.setObjectName("send_btn")
        self.horizontalLayout.addWidget(self.send_btn)
        self.clear_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.clear_btn.sizePolicy().hasHeightForWidth())
        self.clear_btn.setSizePolicy(sizePolicy)
        self.clear_btn.setObjectName("clear_btn")
        self.horizontalLayout.addWidget(self.clear_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        chat_interface.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(chat_interface)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 687, 22))
        self.menubar.setObjectName("menubar")
        chat_interface.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(chat_interface)
        self.statusbar.setObjectName("statusbar")
        chat_interface.setStatusBar(self.statusbar)

        self.retranslateUi(chat_interface)
        QtCore.QMetaObject.connectSlotsByName(chat_interface)

    def retranslateUi(self, chat_interface):
        _translate = QtCore.QCoreApplication.translate
        chat_interface.setWindowTitle(_translate("chat_interface", "MainWindow"))
        self.text_input.setPlaceholderText(_translate("chat_interface", "输入消息..."))

        self.send_btn.setText(_translate("chat_interface", "提交"))
        self.clear_btn.setText(_translate("chat_interface", "清空"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    chat_interface = QtWidgets.QMainWindow()
    ui = Ui_chat_interface()
    ui.setupUi(chat_interface)
    chat_interface.show()
    sys.exit(app.exec_())
